### ISSUE TITLE
Number type support?

### ISSUE THREAD

**Issue by bigdrum** [jspears/subschema#11]
Hello, I wonder how to specify the schema so that the value is parsed into number?

**Comment by jspears** [comment]
I implemented a Number type in 0.9.2 -   I started explaining how to do it,
and well... Let me know if this works.

**Comment by bigdrum** [comment]
Thanks for quick response. But seems it doesn't support input integers.

The following branch matches integer and prevent it being set to the value manager.
```
//Not a valid number but valid to become a number
if (/^(-\.|-|)[0-9]*\.?$/.test(value)) {
```

**Comment by jspears** [comment]
yeah, was a little quick to release.  I think its fixed.   But don't have
time to do anything thorough until tonight.

**Comment by jspears** [comment]
I think its fixed.  Let me know if you have any issues with this.
