### ISSUE TITLE
IE10 Promises

### ISSUE THREAD

**Issue by kiranvenkatesh** [jspears/subschema#17]
I just started to test m forms in IE10 and I am seeing the following error,

'Promise' is undefined.

Do need to provide a wrapper for the same? I am tracing this to Editor.js in src/

**Comment by jspears** [comment]
Yeah, sorry about that.   At the bottom of you will see the thing 
https://github.com/jspears/subschema-simple-example/blob/master/hot.webpack.config.js
  new webpack.ProvidePlugin({
            Promise: "native-promise-only"
        }),

Which provides a global Promise.   I need to make sure the precompiled one uses it and should do a window.Promise check in the Editor to prevent that from happening.

**Comment by kiranvenkatesh** [comment]
We have creating a small vendor file to provide us with necessary globals. So for now the IE10 issue is resolved.

I will keep an eye out for a new version. cheers!

**Comment by jspears** [comment]
Fixed in latest version, thanks for the report.
