### ISSUE TITLE
Hidden prevents other examples from loading

### ISSUE THREAD

**Issue by winkler1** [jspears/subschema#2]
Demo screencast-- http://screencast.com/t/HjlifLbMU6n6

**Comment by jspears** [comment]
Doh... I think I had fixed and not updated the gh-pages.  It *works for me*  in the latest gh-page update.   I'll do some more testing before calling it working.

Thanks for the report.

**Comment by jspears** [comment]
Ended up rewriting the sample app, so its much better, and seems to be working correctly.   Be great if you could check it out again.  I think I am getting the hang of gh-pages.

**Comment by winkler1** [comment]
Whoah - fancy!
