### ISSUE TITLE
Validation not triggered if directly submitting the form instead of focusing on the fields

### ISSUE THREAD

**Issue by rvramesh** [jspears/subschema#3]
Steps to Reproduce

1. Goto http://jspears.github.io/subschema/?#/Login
2. Click on  "Login" Button.

Expected : Username is required error
Actual :  Page gets reloaded

If I place the focus on Username field and then press login the error is displayed as expected.

**Comment by jspears** [comment]
Thanks for the bug report. Its fixed.
