### ISSUE TITLE
Pre-built version on npm

### ISSUE THREAD

**Issue by scoarescoare** [jspears/subschema#4]
Hey, I am very interested in your library. I've been evaluating several lately, but a lot of them seem to really abstract the rendered output of a form, making it difficult to customize your output. I know [others feel the same way] (http://www.reddit.com/r/reactjs/comments/383e99/good_patterns_for_forms/).

On that note, I'm finding it difficult to get up and running with subschema because I'm trying to incorporate it into my own project, as opposed to clone your repo and start there (with webpack, etc). 

This other github issue explains the why's/hows of publishing pre-built jsx to npm: prometheusresearch/react-forms#42

**Comment by jspears** [comment]
Be happy to consider any patches.   I've gone back in forth between offering prebuilt js and basically requiring webpack.  Pros and Cons for both.  Let me know what issues you are having I may be able to help.    

Adding to the complication, is I have a react-native version, which makes packaging super tricky.  I hope to publish that extension shortly.

**Comment by scoarescoare** [comment]
I'm having issues importing subschema. I'm jusing [jspm](http://jspm.io/) so when I try to import the subschema module, it errors because of jsx 'unexpected token' and importing subschema's dependencies.

If there's a way to pre-build a copy with webpack, then I could probably get around everything. 

I noticed the `webpack` npm command, but I think even the output of that had some `require`'s  given that it was trying to import another file when I tried that approach. I didn't spend too much time on this part though.

**Comment by jspears** [comment]
Yes, I'll get it to do that shortly, 
jspm-
**Frictionless browser package management** 

don't we wish.

**Comment by jspears** [comment]
So I added a prebuilt js file and set the browser tag to it.   Let me know if this works, reopen if it doesn't.

Any feedback is appreciated.

**Comment by scoarescoare** [comment]
Awesome, thanks.
