### ISSUE TITLE
Get entity object on valid form submit

### ISSUE THREAD

**Issue by brabeji** [jspears/subschema#5]
Hello, I like subschema a lot so I want to use it for my next project.

I didn't find a way to pull entity object from form on submit, is this implemented? I suppose this functionality would incorporate ValueManager but I can't find much of docs for it.

Thank you!

**Comment by brabeji** [comment]
Ok, I found my precious entity in `property` argument of onSubmit callback although argument naming seems wrong. I am getting:

```
onSubmit: function(event, errors, entity, path) {}
```

**Comment by jspears** [comment]
form.getValue() will return the values
